### ISSUE TITLE
Crawl_GroupPosts 結果為 break_times ...

### ISSUE THREAD

**Issue by zhChenOuO** [TLYu0419/facebook_crawler#7]
想請問一下

下面是範例的程式碼

```python
import facebook_crawler
groupurl = 'https://www.facebook.com/groups/pythontw'
facebook_crawler.Crawl_GroupPosts(groupurl, until_date='2021-01-01’)
```
但結果是

break_times: 1
break_times: 2
break_times: 3
break_times: 4
break_times: 5
break_times: 6

**Comment by erba994** [comment]
same here

**Comment by weberlu88** [comment]
FB 的 XHR 連結改了喔! 套件無法使用了~
同樣的範例程式碼，錯誤訊息如下:

`/usr/local/lib/python3.7/dist-packages/facebook_crawler.py in get_pageid(pageurl)
     19                   'sec-fetch-mode': 'navigate'}
     20         resp = requests.get(pageurl, headers=headers)
---> 21         pageid = re.findall('page_id=(.*?)"',resp.text)[0]
     22     return pageid
     23 

IndexError: list index out of range`

**Comment by TLYu0419** [comment]
I've published a new version(0.0.25) of the facebook_crawler. You uninstall the old version and install the latest version.
Please feel free to contact me if you have any questions. Thanks!

**Comment by darkjackx** [comment]
get another problem

>>> import facebook_crawler
>>> groupurl = 'https://www.facebook.com/groups/934234496602432'
>>> facebook_crawler.Crawl_GroupPosts(groupurl, until_date='2021-01-01')

TimeStamp: 2021-12-14.
TimeStamp: 2021-12-13.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\darkj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\facebook_crawler.py", line 216, in Crawl_GroupPosts
    df = pd.merge(left=content_df, right=feedback_df, how='left', on='POSTID')
  File "C:\Users\darkj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\core\reshape\merge.py", line 87, in merge
    validate=validate,
  File "C:\Users\darkj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\core\reshape\merge.py", line 656, in __init__
    self._maybe_coerce_merge_keys()
  File "C:\Users\darkj\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\core\reshape\merge.py", line 1165, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on object and int64 columns. If you wish to proceed you should use pd.concat

**Comment by TLYu0419** [comment]
@darkjackx 
Have a look at this ipynb file, and I will fix it in the next version, thanks!
https://github.com/TLYu0419/facebook_crawler/blob/main/sample/GroupCrawler_20220420.ipynb
